version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - 2883:2883
      - 9001:9001
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
  recon:
    build:
      context: ./recon
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=2883
