version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    volumes:
      - ${PWD}/docker-compose/etc/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquito/data
    deploy:
      resources:
        limits:
          memory: 10M

volumes:
  mosquitto_data:
