version: '3'

services:
  webapp:
    build:
      context: ../webapp
    depends_on:
      - mosquitto
      - recon
      - authelia
    volumes:
      - webapp_data:/data
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=2883
      - DATA_DIR=/data
    deploy:
      resources:
        limits:
          memory: 100M

volumes:
  webapp_data:
