apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-map
data:
  OPEN_OBSERVE_BASE_URL: http://localhost:5080
  MQTT_HOST: mosquitto-service
  MQTT_PORT: '2883'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: eclipse-mosquitto:2.0
          ports:
            - containerPort: 8000
          env:
            - name: OPEN_OBSERVE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: webapp-map
                  key: OPEN_OBSERVE_BASE_URL
            - name: MQTT_HOST
              valueFrom:
                configMapKeyRef:
                  name: webapp-map
                  key: MQTT_HOST
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  name: webapp-map
                  key: MQTT_PORT
            - name: DATA_DIR
              value: /data
          volumeMounts:
            - name: webapp-data-pvc
              mountPath: /data
          resources:
            limits:
              memory: 100Mi
      volumes:
        - name: webapp-data-pvc
          persistentVolumeClaim:
            claimName: webapp-data-pvc
