clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /var/lib/promtail/positions.yaml

scrape_configs:
  - job_name: recon-logs
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /logs/*.log
          service: recon
