###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: 6fa67a3040474cf0b431ef3c6b05972964881f2f45f6f1141a3af69cffb4ecb1
default_redirection_url: https://auth.star-lord.net

server:
  host: 0.0.0.0
  port: 9091
  path: ''
  buffers:
    read: 4096
    write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ''
    certificate: ''
  asset_path: /config/assets

log:
  level: info

totp:
  issuer: star-lord.net
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yaml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: one_factor
  rules:
  - domain: 'grafana.star-lord.net'
    policy: bypass

session:
  name: authelia_session
  secret: b222afe989960424a3e5dcf2f0530997c7be44823b1eb4fc078b775688e5037c
  expiration: 1h
  inactivity: 5m
  domain: star-lord.net

regulation:
  max_retries: 5
  find_time: 5m
  ban_time: 5m

storage:
  encryption_key: 069e514662d2673973e9dcd4ce4533b1577659050f97ee6d60301291cea29431
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_providers:
  oidc:
    hmac_secret: 0b74807be5fd9ccc3a175f9d63f51697879dc9277a52ed00aeb34f06ec81369e
    issuer_private_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDsUwcz6byd58g6
      YK1ho7DO/+OAn/jy6cDEkcbc0O4E0ShUfbLiNPygoA7l/Bwrywihux6KGHU5OZOZ
      82GgtCk5HKR4yQtQe2lBvLRTXGPbN97jfjuxGs0P3ALJn7u/uDXSLNh/6DjwzItS
      d79E1l1yWLZNPlkHK2NSM9VwvPnQdPTAi2K+E0C8QXteWe2EhreA8ABn4GAaWyXC
      uH4OFHH1/HKDM1FIE0yqSC2ReYAwh34K+BKpuMcjg1ocm5r7H1YfODkaG7c0yN+Y
      Yx2p/pSxDmTsXTNfyR2TemDzowFX4WowcxI13Ht9t0gP+TksGwLfSD9/vte0/gTW
      E6i1vlfvAgMBAAECggEAHfpsU/wHBrrjze/8noGuyJtyRxtD78CSSP07DkDcqLTF
      mm41lndlQpT7PtZr1mxThHyho5/1otQ4cpOKo2GnRwzomj/alROKpyGieF6kdicQ
      uagGN3GwaJ4epmgCX5AlF6vDrPoO2xD/bW8uTrOot/wj6AmMLpok58UWgs4eHICz
      LWQ0TFDSvpawotHPkuVycP0WRsZL19Ksy172osepve7UWp+uivMeKOr5XGnr/kAF
      1wqBkAxHx3UCA8Xa5647ieCT9gyhA54/XV66phsMiT/ilujF5bMwtoybpBn2xGqh
      /3lLSwiAMNPPH1nWrXh5epKMnwwYzGb3qHXDi63n9QKBgQD8HXWMzw8BXEGz4auG
      RQDJNWK8JmuArk5yebSMtQNgRNLIt84vuchswDE76XwXSEfqDv5tYOvcehi+NGYr
      iN53z5GLQxlMAqon6IduhzkHMugb5t3/nTIaimGmolNlEcvHLlYg84fJy4ds4DzM
      98XQGvKhki8nJKqLf0Hu35RvTQKBgQDv90cdT9ekQat11p1czYaZD7BU/wCb62UK
      6+dpnnct0ZntP6dshJ5SM93Akz3ssnuXZn5wQbUadgdsuR1JtUFep3hPMVqrm5Q1
      uGKO4ovTic6nCiqSopPbtINQGulRtiT1g/16lkuKp8tRUerzUNuslW92P3MGoYv2
      YKULcMc+KwKBgQC/T4966UimrJ5C5NUmz0fYZ0VkJvder2Zh4c7LEzTboX4dx7ST
      bLQVKgZyQyvh8vx3NSeGUozIQnJyKwr4sCS43+6+sY0Jq9/45q+WhNAWkV+mhJsj
      M+LoVufg7b7ArC9pFtVOrd31mBdM3B/nHYGi+D/zsR1M47rynf+nR0u45QKBgH0r
      ZhvjDt+uJYrVBMZoqoHijh732NB76/vTa6VLNG1g/MKlRmazkoXcahpOc6movBEQ
      NHnHvHjuAhdzQ9SzyEJgZsAgRWRoRdnzsO1JPJh+NJ4rDmPoi+m5chlxwCyQLx0l
      2S19gi/0MHjdmwmKLtwKItbyZ8SYtZIxfUXHcRZ7AoGAAlTOthoHXwonFXPKni/v
      izn4tLvK1SMH4Hm28faDPW64MyFJBMVixqHB5bbTYN0aA2Pfexs4QFXwmTfusy6/
      ifENWUXdaeT6+ZNvxoe0ET/6/L7n722/ehTR5CtYaka4Q33+pRiqjmNqDJdmjIcu
      o1vmqrRHBScNBg/QWAblXgY=
      -----END PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins_from_client_redirect_uris: false
    clients:
    - id: grafana
      description: Grafana
      secret: '$argon2id$v=19$m=65536,t=3,p=4$Jbwkw7YWN5DfEt7HwFXwvg$qd6t4MQiPdJTslX4l84SplZFrjVeE/vSyosMWzkMZCs'
      public: false
      authorization_policy: one_factor
      redirect_uris:
        - https://grafana.star-lord.net/login/generic_oauth
      scopes:
        - openid
        - profile
        - email
        - groups
      userinfo_signing_algorithm: none
