name: Publish Recon Image

on:
  push:
    branches:
      - master
    paths:
      - recon/**

jobs:
  push_to_registry:
    name: Push recon image to DigitalOcean Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build image
        run: >-
          docker build
          --tag registry.digitalocean.com/star-lord-cr/recon:latest
          -f ./recon/dockerfile
          ./recon/
      - name: Log in to DigitalOcean Container Registry
        run: >-
          echo ${{ secrets.DIGITAL_OCEAN_API_TOKEN }} |
          docker login
          --username ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
          --password-stdin registry.digitalocean.com
      - name: Push image to DigitalOcean Container Registry
        run: docker image push registry.digitalocean.com/star-lord-cr/recon:latest
      - name: Log out from DigitalOcean Container Registry
        run: docker logout registry.digitalocean.com
